"""add case_conditions and run verdict

Revision ID: 2249739f3e11
Revises: 0104ddc0de58
Create Date: 2026-10-07 18:53:49.847410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2249739f3e11'
down_revision: Union[str, Sequence[str], None] = '0104ddc0de58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('opened_in_run_id', sa.UUID(), nullable=True),
    sa.Column('resolved_in_run_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by_document_id', sa.UUID(), nullable=True),
    sa.Column('waived_by', sa.String(length=256), nullable=True),
    sa.Column('waived_reason', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opened_in_run_id'], ['case_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_in_run_id'], ['case_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('case_runs', sa.Column('verdict', sa.String(length=32), nullable=True))
    op.add_column('case_runs', sa.Column('verdict_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_runs', 'verdict_reasons')
    op.drop_column('case_runs', 'verdict')
    op.drop_table('case_conditions')
    # ### end Alembic commands ###
