"""prompt edits (VRT-63)

Revision ID: 59ced5801c3a
Revises: f775ca0ac7be
Create Date: 2026-10-09 08:37:57.885221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ced5801c3a'
down_revision: Union[str, Sequence[str], None] = 'f775ca0ac7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_edits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_by', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['eval_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_edits_one_draft', 'prompt_edits', ['name'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    op.create_index('ix_prompt_edits_one_published', 'prompt_edits', ['name'], unique=True, postgresql_where=sa.text("status = 'published'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompt_edits_one_published', table_name='prompt_edits', postgresql_where=sa.text("status = 'published'"))
    op.drop_index('ix_prompt_edits_one_draft', table_name='prompt_edits', postgresql_where=sa.text("status = 'draft'"))
    op.drop_table('prompt_edits')
    # ### end Alembic commands ###
