"""a2a tasks vrt 52

Revision ID: 8303157dc9cd
Revises: dc172b953183
Create Date: 2026-10-10 07:00:35.284216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8303157dc9cd'
down_revision: Union[str, Sequence[str], None] = 'dc172b953183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a2a_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('context_id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_a2a_tasks_context_id'), 'a2a_tasks', ['context_id'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_owner'), 'a2a_tasks', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_a2a_tasks_owner'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_context_id'), table_name='a2a_tasks')
    op.drop_table('a2a_tasks')
    # ### end Alembic commands ###
