"""case run reprocess scope (VRT-40)

Revision ID: 9a8804127d16
Revises: f7d73ccba074
Create Date: 2026-10-08 21:59:51.130490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a8804127d16'
down_revision: Union[str, Sequence[str], None] = 'f7d73ccba074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_runs', sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_runs', 'scope')
    # ### end Alembic commands ###
