"""rules over attributes with test cases (VRT-36)

Revision ID: bc28a2dcce3c
Revises: ef16eac59e56
Create Date: 2026-10-08 18:37:38.760838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc28a2dcce3c'
down_revision: Union[str, Sequence[str], None] = 'ef16eac59e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_rule_definitions', sa.Column('attribute', sa.String(length=64), nullable=True))
    op.add_column('validation_rule_definitions', sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_rule_definitions', 'test_cases')
    op.drop_column('validation_rule_definitions', 'attribute')
    # ### end Alembic commands ###
