"""outbox published_at vrt 49

Revision ID: dc172b953183
Revises: 4197fc63c20b
Create Date: 2026-10-09 14:15:28.405952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc172b953183'
down_revision: Union[str, Sequence[str], None] = '4197fc63c20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # Events from before the bus existed are history, not news: never published.
    op.execute("UPDATE outbox_events SET published_at = created_at")
    op.create_index('ix_outbox_events_unpublished', 'outbox_events', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_unpublished', table_name='outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_column('outbox_events', 'published_at')
    # ### end Alembic commands ###
