"""bulk jobs vrt 48

Revision ID: e310cf391b2c
Revises: 6abcf33d4355
Create Date: 2026-10-09 12:00:24.978772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e310cf391b2c'
down_revision: Union[str, Sequence[str], None] = '6abcf33d4355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('archive_sha256', sa.String(length=64), nullable=False),
    sa.Column('skipped', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'idempotency_key', name='uq_bulk_jobs_tenant_idempotency_key')
    )
    op.add_column('cases', sa.Column('bulk_job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cases_bulk_job_id'), 'cases', ['bulk_job_id'], unique=False)
    op.create_foreign_key('fk_cases_bulk_job_id', 'cases', 'bulk_jobs', ['bulk_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cases_bulk_job_id', 'cases', type_='foreignkey')
    op.drop_index(op.f('ix_cases_bulk_job_id'), table_name='cases')
    op.drop_column('cases', 'bulk_job_id')
    op.drop_table('bulk_jobs')
    # ### end Alembic commands ###
