"""correction reason code and justification (VRT-39)

Revision ID: f7d73ccba074
Revises: bc28a2dcce3c
Create Date: 2026-10-08 19:30:15.502750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d73ccba074'
down_revision: Union[str, Sequence[str], None] = 'bc28a2dcce3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('reason_code', sa.String(length=32), nullable=True))
    op.add_column('audit_log', sa.Column('justification', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'justification')
    op.drop_column('audit_log', 'reason_code')
    # ### end Alembic commands ###
