#!/usr/bin/env bash
# Interim aeon instance until the shared multi-tenant deployment exists
# (VRT-26, ADR-0003, VRT-AEON-005): the aeon repo's own compose file plus
# deploy/aeon/compose.override.yml — same aeon code, configuration only.
#
#   scripts/aeon_dev.sh setup    # once: tokens (deploy/aeon/secrets/), callers.yaml, AEON_API_TOKEN in .env
#   scripts/aeon_dev.sh up       # build + start temporal, toolgw, worker, runcontroller (+ deps)
#   scripts/aeon_dev.sh status | logs [service] | down
#
# AEON_REPO defaults to the sibling checkout ../aeon-ai.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/deploy/aeon"
AEON_REPO="${AEON_REPO:-$(cd "$ROOT/.." && pwd)/aeon-ai}"
AGENT="veritium-case-run@1.0.0"
SERVICES=(temporal temporal-db temporal-ui postgres searxng toolgw worker runcontroller)

sha() { printf '%s' "$1" | shasum -a 256 | cut -d' ' -f1; }

setup() {
  mkdir -p "$DIR/secrets" "$DIR/artifacts"
  for name in api_token worker_token; do
    [ -s "$DIR/secrets/$name" ] || { openssl rand -hex 32 | tr -d '\n' > "$DIR/secrets/$name"; chmod 600 "$DIR/secrets/$name"; }
  done
  cat > "$DIR/callers.yaml" <<YAML
# GENERATED by scripts/aeon_dev.sh setup — hashes only; the tokens live in deploy/aeon/secrets/ (gitignored).
apiVersion: harness.ai/v1
kind: CallerBundle
callers:
  - id: veritium-api          # submits case runs (POST /runs)
    kind: service
    tenant: veritium
    tokenSHA256: "$(sha "$(cat "$DIR/secrets/api_token")")"
    mayActAs: [$AGENT]
    mayApprove: false
  - id: veritium-aeon-worker  # aeon's worker: checks each activity's policy as the run's agent
    kind: service
    tenant: veritium
    tokenSHA256: "$(sha "$(cat "$DIR/secrets/worker_token")")"
    mayActAs: [$AGENT]
    mayApprove: false
YAML
  if ! grep -q '^AEON_API_TOKEN=' "$ROOT/.env" 2>/dev/null; then
    printf '\n# Token de Veritium ante su despliegue de aeon (VRT-26). Generado por scripts/aeon_dev.sh setup.\nAEON_API_TOKEN=%s\n' "$(cat "$DIR/secrets/api_token")" >> "$ROOT/.env"
  fi
  echo "listo: callers.yaml generado, tokens en $DIR/secrets/, AEON_API_TOKEN en .env"
}

compose() {
  [ -f "$AEON_REPO/deploy/compose/docker-compose.yml" ] || { echo "no encuentro aeon en $AEON_REPO (definir AEON_REPO)"; exit 1; }
  [ -s "$DIR/secrets/worker_token" ] || { echo "falta setup: scripts/aeon_dev.sh setup"; exit 1; }
  VERITIUM_AEON_DIR="$DIR" AEON_CALLERS_PATH=/veritium/callers.yaml AEON_CALLER_TOKEN="$(cat "$DIR/secrets/worker_token")" \
    docker compose -p veritium-aeon -f "$AEON_REPO/deploy/compose/docker-compose.yml" -f "$DIR/compose.override.yml" --profile core "$@"
}

case "${1:-}" in
  setup) setup ;;
  # One image at a time: Docker Desktop's BuildKit refuses parallel builds
  # ("only one connection allowed").
  up) for s in toolgw worker runcontroller; do compose build "$s"; done; compose up -d "${SERVICES[@]}" ;;
  down) compose down ;;
  status) compose ps ;;
  logs) shift; compose logs --tail=100 "$@" ;;
  *) sed -n '2,10p' "$0"; exit 1 ;;
esac
